const mongoose = require('mongoose');

const postSchema = mongoose.Schema({
  // to save the autogenerated id to 'user'...and refer it to the User collection
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  username: { type: String, default: '' },
  post: { type: String, default: '' },
  comments: [
    {
      userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
      username: { type: String, default: '' },
      comment: { type: String, default: '' },
      createdAt: { type: Date, default: Date.now() }
    }
  ],
  totalLikes: { type: Number, default: 0 },
  likes: [
    {
      username: { type: String, default: '' }
    }
  ],
  created: { type: Date, default: Date.now() }
});

module.exports = mongoose.model('Post', postSchema);
